### ISSUE TITLE
Missing key(s) in state_dict while loading FastPitch during inference

### ISSUE THREAD

**Issue by dan-ya** [dan-wells/fastpitch#3]
I try to generate the speech using previously trained FastPitch model. But I have an issue with loading a FastPitch model.
What could be a reason for this kind of error?

```
DLL 2024-04-10 17:00:26.559291 - PARAMETER | input:  test_data/test_text.txt
DLL 2024-04-10 17:00:26.559356 - PARAMETER | output:  test_data
DLL 2024-04-10 17:00:26.559374 - PARAMETER | dataset_path:  
DLL 2024-04-10 17:00:26.559387 - PARAMETER | log_file: 
DLL 2024-04-10 17:00:26.559398 - PARAMETER | cuda:  False
DLL 2024-04-10 17:00:26.559413 - PARAMETER | cudnn_benchmark:  False
DLL 2024-04-10 17:00:26.559424 - PARAMETER | fastpitch:  pretrained_models/fastpitch/fastpitch_700.pt
DLL 2024-04-10 17:00:26.559437 - PARAMETER | hifigan:  pretrained_models/hifigan/hifigan_gen_checkpoint_10000_ft.pt
DLL 2024-04-10 17:00:26.559448 - PARAMETER | hifigan_config:  hifigan/config/config_v1.json
DLL 2024-04-10 17:00:26.559459 - PARAMETER | sampling_rate:  22050
DLL 2024-04-10 17:00:26.559470 - PARAMETER | stft_hop_length:  256
DLL 2024-04-10 17:00:26.559483 - PARAMETER | denoising_strength:  0.0
DLL 2024-04-10 17:00:26.559493 - PARAMETER | save_mels:  False
DLL 2024-04-10 17:00:26.559504 - PARAMETER | amp:  False
DLL 2024-04-10 17:00:26.559778 - PARAMETER | batch_size:  64
DLL 2024-04-10 17:00:26.559844 - PARAMETER | warmup_steps:  0
DLL 2024-04-10 17:00:26.559863 - PARAMETER | repeats:  1
DLL 2024-04-10 17:00:26.559876 - PARAMETER | ema:  False
DLL 2024-04-10 17:00:26.559890 - PARAMETER | fade_out:  10
DLL 2024-04-10 17:00:26.559902 - PARAMETER | pace:  1.0
DLL 2024-04-10 17:00:26.559913 - PARAMETER | pitch_transform_flatten:  False
DLL 2024-04-10 17:00:26.559924 - PARAMETER | pitch_transform_invert:  False
DLL 2024-04-10 17:00:26.559936 - PARAMETER | pitch_transform_amplify:  1.0
DLL 2024-04-10 17:00:26.559948 - PARAMETER | pitch_transform_shift:  0.0
DLL 2024-04-10 17:00:26.559959 - PARAMETER | pitch_transform_custom:  False
DLL 2024-04-10 17:00:26.559970 - PARAMETER | input_type:  char
DLL 2024-04-10 17:00:26.559981 - PARAMETER | symbol_set:  english_basic
DLL 2024-04-10 17:00:26.559992 - PARAMETER | text_cleaners:  []
DLL 2024-04-10 17:00:26.560006 - PARAMETER | speaker_ids:  pretrained_models/speaker_ids.txt
DLL 2024-04-10 17:00:26.560017 - PARAMETER | speaker:  ljs
DLL 2024-04-10 17:00:26.560028 - PARAMETER | lang_ids:  pretrained_models/style_ids.txt
DLL 2024-04-10 17:00:26.560039 - PARAMETER | language:  neutral
Traceback (most recent call last):
  File "inference.py", line 544, in <module>
    main()
  File "inference.py", line 362, in main
    generator = load_and_setup_model(
  File "inference.py", line 177, in load_and_setup_model
    model = load_model_from_ckpt(checkpoint, ema, model, device)
  File "inference.py", line 153, in load_model_from_ckpt
    status += ' ' + str(model.load_state_dict(sd))
  File "/opt/anaconda3/envs/TORCH/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FastPitch:
	Missing key(s) in state_dict: "attention.attn_proj.weight", "attention.attn_proj.bias". 

```

I run inference with a following command line:
```
python inference.py \
  --input test_data/test_text.txt \
  --output test_data\
  --fastpitch pretrained_models/fastpitch/fastpitch_700.pt \
  --input-type char \
  --symbol-set english_basic \
  --hifigan pretrained_models/hifigan/hifigan_gen_checkpoint_10000_ft.pt \
  --hifigan-config hifigan/config/config_v1.json \
  --speaker-ids pretrained_models/speaker_ids.txt \
  --lang-ids pretrained_models/style_ids.txt \
  --speaker ljs \
  --language neutral \
  --use-mas
```

And the model has been trained with a following command line:
```
python train.py \
  --dataset-path $DATA_ROOT \
  --output models \
  --training-files $DATA_ROOT/expresso_fs_style.meta.train.txt \
  --validation-files $DATA_ROOT/expresso_fs_style.meta.val.txt \
  --pitch-mean-std-file $DATA_ROOT/pitches_stats__expresso_fs_style.json \
  --speaker-ids $DATA_ROOT/speaker_ids.txt \
  --lang-ids $DATA_ROOT/style_ids.txt \
  --input-type char \
  --symbol-set english_basic \
  --epochs 1000 \
  --epochs-per-checkpoint 20 \
  --batch-size 64 \
  --resume \
  --use-mas \
  --cuda
```

**Comment by dan-wells** [comment]
Those are precisely the unused parameters recently removed in https://github.com/dan-wells/fastpitch/commit/566126e85385d80ee36eb7c97a033a682f9799b3: can you make sure you don't still have that `attn_proj` line in your `fastpitch/attention.py`?

As a quick workaround, you can probably just add `strict=False` to the `model.load_state_dict()` call here: https://github.com/dan-wells/fastpitch/blob/main/inference.py#L153
Since those parameters have always been unused, it shouldn't have any impact whether or not the weights are actually loaded.

It doesn't make sense to me that this error could crop up though -- it seems like you'd have to have trained the model without `attn_proj` in it (i.e. using the latest commit), and then be synthesising with a model definition from before I removed it...

**Comment by dan-ya** [comment]
Thank you for your help! It did help me. I indeed had two copies of your repository on different machines: one for training and one for generation. I have not updated the later one. Now it is fine!
BTW, `strict=False` flag is a good workaround as well.
